services:
  minio:
    image: bitnami/minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio_network
    volumes:
      - minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=abcdefghijkl
      - MINIO_DEFAULT_BUCKETS=mybucket
      - MINIO_SERVER_URL=http://127.0.0.1:9000

networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local