#!/usr/bin/env bash

mkdir -p /tmp/thisdir
head -c 49M /dev/urandom > /tmp/thisdir/test1.dat
head -c 61M /dev/urandom > /tmp/thisdir/test2.dat
head -c 42M /dev/urandom > /tmp/thisdir/test3.dat
head -c 101M /dev/urandom > /tmp/thisdir/test4.dat
head -c 201M /dev/urandom > /tmp/thisdir/test5.dat
head -c 301M /dev/urandom > /tmp/thisdir/test6.dat
head -c 51M /dev/urandom > /tmp/thisdir/test7.dat
head -c 1M /dev/urandom > /tmp/thisdir/test8.dat
head -c 21M /dev/urandom > /tmp/thisdir/test9.dat
head -c 39M /dev/urandom > /tmp/thisdir/test10.dat
head -c 63M /dev/urandom > /tmp/thisdir/test11.dat
head -c 42M /dev/urandom > /tmp/thisdir/test12.dat
head -c 1M /dev/urandom > /tmp/thisdir/test13.dat
head -c 201M /dev/urandom > /tmp/thisdir/test14.dat
head -c 301M /dev/urandom > /tmp/thisdir/test15.dat
head -c 51M /dev/urandom > /tmp/thisdir/test16.dat
head -c 1M /dev/urandom > /tmp/thisdir/test17.dat
head -c 21M /dev/urandom > /tmp/thisdir/test18.dat
head -c 3M /dev/urandom > /tmp/thisdir/test19.dat
head -c 11M /dev/urandom > /tmp/thisdir/test20.dat
head -c 49M /dev/urandom > /tmp/thisdir/test21.dat
head -c 61M /dev/urandom > /tmp/thisdir/test22.dat
head -c 42M /dev/urandom > /tmp/thisdir/test23.dat
head -c 101M /dev/urandom > /tmp/thisdir/test24.dat
head -c 201M /dev/urandom > /tmp/thisdir/test25.dat
head -c 301M /dev/urandom > /tmp/thisdir/test26.dat
head -c 51M /dev/urandom > /tmp/thisdir/test27.dat
head -c 1M /dev/urandom > /tmp/thisdir/test28.dat
head -c 21M /dev/urandom > /tmp/thisdir/test29.dat
head -c 39M /dev/urandom > /tmp/thisdir/test30.dat
head -c 63M /dev/urandom > /tmp/thisdir/test31.dat
head -c 42M /dev/urandom > /tmp/thisdir/test32.dat
head -c 1M /dev/urandom > /tmp/thisdir/test33.dat
head -c 201M /dev/urandom > /tmp/thisdir/test34.dat
head -c 301M /dev/urandom > /tmp/thisdir/test35.dat
head -c 51M /dev/urandom > /tmp/thisdir/test36.dat
head -c 1M /dev/urandom > /tmp/thisdir/test37.dat
head -c 21M /dev/urandom > /tmp/thisdir/test38.dat
head -c 3M /dev/urandom > /tmp/thisdir/test39.dat
head -c 11M /dev/urandom > /tmp/thisdir/test40.dat
