services:
  minio:
    image: bitnami/minio
    container_name: s3-glacier-deep-archive-backup-testing-db
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - s3-glacier-deep-archive-backup-testing-network
    volumes:
      - s3-glacier-deep-archive-backup-testing-data:/bitnami/minio/data
    environment:
      - TZ=${TZ}
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=abcdefghijkl
      - MINIO_DEFAULT_BUCKETS=mybucket
      - MINIO_SERVER_URL=http://127.0.0.1:9000

networks:
  s3-glacier-deep-archive-backup-testing-network:
    driver: bridge

volumes:
  s3-glacier-deep-archive-backup-testing-data:
    driver: local
